# Project3 - Document\Article   Classification\Identification

In [ ]:
# Author - Sandip Datta
# Nov - 2016

In [194]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Data Collection

In [195]:
# Data Container for all articles
data = []

In [196]:
# Read the entire article as a single string .
# Remove newline charater \n

file = open("article1.txt", "r")

data_1 = file.read().replace('\n','')
data_1 = unicode(data_1, errors='ignore')

#data_1.lower()

data.append(data_1)

#print data_1
#data_1

In [197]:
file = open("article2.txt", "r")
data_2 = file.read().replace('\n','')
data_2 = unicode(data_2, errors='ignore')

data.append(data_2)

In [198]:
file = open("article3.txt", "r")
data_3 = file.read().replace('\n','')
data_3 = unicode(data_3, errors='ignore')
data.append(data_3)

In [199]:
file = open("article4.txt", "r")
data_4 = file.read().replace('\n','')
data_4 = unicode(data_4, errors='ignore')
data.append(data_4)

In [200]:
type(data)

list

# Instantiate TF-IDF Model

In [201]:
from sklearn.feature_extraction.text import TfidfVectorizer

Tf = TfidfVectorizer(stop_words='english')


In [202]:
#TfidfVectorizer()

# TF-IDF Matrix

In [203]:
dataTfMatrix = Tf.fit_transform(data)

In [204]:
dataTfMatrix.shape

(4, 1014)

In [205]:
dataTfMatrix

<4x1014 sparse matrix of type '<type 'numpy.float64'>'
	with 1143 stored elements in Compressed Sparse Row format>

# Match the Articles for Similarity

# Cosine Similarity

In [206]:
# The higher score , the more chnaces of being similar

from sklearn.metrics.pairwise import cosine_similarity

cosine_similarity(dataTfMatrix[0],dataTfMatrix[1])

array([[ 0.03582307]])

In [207]:
cosine_similarity(dataTfMatrix[0],dataTfMatrix[2])

array([[ 0.01256609]])

In [208]:
cosine_similarity(dataTfMatrix[0],dataTfMatrix[3])

array([[ 0.27520458]])

In [209]:
'''The tfidf_matrix[0:1] is the Scipy operation to get the first row of the sparse matrix and the resulting array is the 
Cosine Similarity between the first document with all documents in the set. Note that the first value of the array is 1.0 
because it is the Cosine Similarity between the first document with itself. 
'''

cosine_similarity(dataTfMatrix[0:1], dataTfMatrix)

array([[ 1.        ,  0.03582307,  0.01256609,  0.27520458]])

# Mathematical Angles - Degree of the vectors

In [210]:
import math

# We will take cosine_similarity values calculated in the above step and find out the corresponding Angle Degree 
# Main doc i.e 1 & Doc 2
cosine_similarity_12 = 0.03789442
angle_in_radians = math.acos(cosine_similarity_12)
print math.degrees(angle_in_radians)
58.462437107432784

87.8282896973


58.462437107432784

In [211]:
# Main doc i.e 1 & Doc 3
cosine_similarity_13 = 0.01146127
angle_in_radians = math.acos(cosine_similarity_13)
print math.degrees(angle_in_radians)
58.462437107432784

89.3433032232


58.462437107432784

In [212]:
# Main doc i.e 1 & Doc 4
cosine_similarity_14 = 0.1464385
angle_in_radians = math.acos(cosine_similarity_14)
print math.degrees(angle_in_radians)
58.462437107432784

81.5794115804


58.462437107432784

In [ ]:
Conclusion - as we from cosine_similarity scores as well as degree of angle , 